name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7b9a15911f34a7eb4449b845dc9c59dcca29adb6fc65acd53875584b54eb2ea"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
