name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "361f2bce6cd72ad7eee12bad258355d0dee496030ac1c9d0bc9d263d7bd7e299"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
